name: Build and stuff
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test
        uses: ./.github/workflows/actions/test-docker-action/action.yml

